//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _7dtd_svmanager_fix_mvvm.LangResources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_7dtd_svmanager_fix_mvvm.LangResources.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   戻る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Back {
            get {
                return ResourceManager.GetString("UI_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Cancel {
            get {
                return ResourceManager.GetString("UI_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Exit {
            get {
                return ResourceManager.GetString("UI_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規作成(_N) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_NewFile {
            get {
                return ResourceManager.GetString("UI_NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次へ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Next {
            get {
                return ResourceManager.GetString("UI_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開く(_O) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_OpenFIle {
            get {
                return ResourceManager.GetString("UI_OpenFIle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前を付けて保存(_A) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_SaveAsFile {
            get {
                return ResourceManager.GetString("UI_SaveAsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存(_S) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_SaveFIle {
            get {
                return ResourceManager.GetString("UI_SaveFIle", resourceCulture);
            }
        }
    }
}
