//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _7dtd_svmanager_fix_mvvm.LangResources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UpdResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UpdResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_7dtd_svmanager_fix_mvvm.LangResources.UpdResources", typeof(UpdResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {0}が見つかりませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string _0_is_not_found {
            get {
                return ResourceManager.GetString("_0_is_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップデータに更新があります。
        ///アップデートの前にアップデータの更新を行います。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string new_updater {
            get {
                return ResourceManager.GetString("new_updater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お知らせ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   notice.ja.xml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Notice_XmlName {
            get {
                return ResourceManager.GetString("Notice_XmlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全て解除する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_AllDeSelect {
            get {
                return ResourceManager.GetString("UI_AllDeSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全て選択する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_AllSelect {
            get {
                return ResourceManager.GetString("UI_AllSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_CancelBT {
            get {
                return ResourceManager.GetString("UI_CancelBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *クリーン対象でなくても更新時差分に含まれている場合は書き換えられます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_CleanNotice {
            get {
                return ResourceManager.GetString("UI_CleanNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クリーンアップデート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_CleanUpdBT {
            get {
                return ResourceManager.GetString("UI_CleanUpdBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在のバージョン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_CurrentVersionLabel {
            get {
                return ResourceManager.GetString("UI_CurrentVersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最新のバージョン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_LatestVersionLabel {
            get {
                return ResourceManager.GetString("UI_LatestVersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   読み込み中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_LoadingName {
            get {
                return ResourceManager.GetString("UI_LoadingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップデート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_UpdBT {
            get {
                return ResourceManager.GetString("UI_UpdBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_UpdFormName {
            get {
                return ResourceManager.GetString("UI_UpdFormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップデータ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Updater {
            get {
                return ResourceManager.GetString("Updater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   updates.ja.xml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Updater_XMLNAME {
            get {
                return ResourceManager.GetString("Updater_XMLNAME", resourceCulture);
            }
        }
    }
}
