//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Updater.LangResources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Updater.LangResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   直接起動はできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cannot_start_directly {
            get {
                return ResourceManager.GetString("Cannot_start_directly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象ファイルをクリーンしています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cleaning_files {
            get {
                return ResourceManager.GetString("Cleaning_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップデートファイルをダウンロードしています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Downloading_the_update_file {
            get {
                return ResourceManager.GetString("Downloading_the_update_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップデートファイルを解凍しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Extracting_the_update_file {
            get {
                return ResourceManager.GetString("Extracting_the_update_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クリーンが完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Finished_cleaning {
            get {
                return ResourceManager.GetString("Finished_cleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップデートが完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Finished_updating {
            get {
                return ResourceManager.GetString("Finished_updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   引数が不正です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Invaild_Argument {
            get {
                return ResourceManager.GetString("Invaild_Argument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップデートを開始します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Start_Update {
            get {
                return ResourceManager.GetString("Start_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーションの終了を待機しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Waiting_for_the_Application_end {
            get {
                return ResourceManager.GetString("Waiting_for_the_Application_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   警告 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
