//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _7dtd_svmanager_fix_mvvm.LangResources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_7dtd_svmanager_fix_mvvm.LangResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {0}が{1}です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string _0_is_1 {
            get {
                return ResourceManager.GetString("_0_is_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が空です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string _0_is_Empty {
            get {
                return ResourceManager.GetString("_0_is_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が不正です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string _0_Is_Invalid {
            get {
                return ResourceManager.GetString("_0_Is_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が見つかりませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string _0_is_not_found {
            get {
                return ResourceManager.GetString("_0_is_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アドレス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アドミンファイルパス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AdminFilePath {
            get {
                return ResourceManager.GetString("AdminFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   既に接続されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AlreadyConnected {
            get {
                return ResourceManager.GetString("AlreadyConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Config Editor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigEditor {
            get {
                return ResourceManager.GetString("ConfigEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コンフィグファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigFile {
            get {
                return ResourceManager.GetString("ConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コンフィグファイルパス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigFilePath {
            get {
                return ResourceManager.GetString("ConfigFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ja に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Culture_Lang {
            get {
                return ResourceManager.GetString("Culture_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Telnetから切断してからアプリケーションをシャットダウンします。 よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DoYouShutdown {
            get {
                return ResourceManager.GetString("DoYouShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接続に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Failed_Connecting {
            get {
                return ResourceManager.GetString("Failed_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバーに接続されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HasnotBeConnected {
            get {
                return ResourceManager.GetString("HasnotBeConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Input_Some_Value {
            get {
                return ResourceManager.GetString("Input_Some_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KeyConfig_ja.xml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeyConfigPath {
            get {
                return ResourceManager.GetString("KeyConfigPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が見つかりませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Not_Found_0 {
            get {
                return ResourceManager.GetString("Not_Found_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お知らせ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ポート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ポート番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PortNumber {
            get {
                return ResourceManager.GetString("PortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}と{1}で同一のポートが選択されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Same_Port_as_0_has_been_used_in_1 {
            get {
                return ResourceManager.GetString("Same_Port_as_0_has_been_used_in_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバーファイルパス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ServerFilePath {
            get {
                return ResourceManager.GetString("ServerFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Telnetに接続されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TelnetIsBeenConnected {
            get {
                return ResourceManager.GetString("TelnetIsBeenConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アドレス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_AddressLabel {
            get {
                return ResourceManager.GetString("UI_AddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コマンド に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_CommandLabel {
            get {
                return ResourceManager.GetString("UI_CommandLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コンフィグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_ConfigLabel {
            get {
                return ResourceManager.GetString("UI_ConfigLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Telnetで接続 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_ConnectWithTelnet {
            get {
                return ResourceManager.GetString("UI_ConnectWithTelnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   座標 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Coord {
            get {
                return ResourceManager.GetString("UI_Coord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デス数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_DeathLabel {
            get {
                return ResourceManager.GetString("UI_DeathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログを消去 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_DeleteLogBTLabel {
            get {
                return ResourceManager.GetString("UI_DeleteLogBTLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Telnetから切断 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_DisconnectFromTelnet {
            get {
                return ResourceManager.GetString("UI_DisconnectFromTelnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   英語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_EnglishLabel {
            get {
                return ResourceManager.GetString("UI_EnglishLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了(_X) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_ExitBT {
            get {
                return ResourceManager.GetString("UI_ExitBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル(_F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_FileBT {
            get {
                return ResourceManager.GetString("UI_FileBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_FinishedLaunching {
            get {
                return ResourceManager.GetString("UI_FinishedLaunching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   初期設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_FirstSettingBT {
            get {
                return ResourceManager.GetString("UI_FirstSettingBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   体力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_HealthLabel {
            get {
                return ResourceManager.GetString("UI_HealthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ヘルプ(_H) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_HelpBT {
            get {
                return ResourceManager.GetString("UI_HelpBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_IDLabel {
            get {
                return ResourceManager.GetString("UI_IDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日本語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_JapaneseLabel {
            get {
                return ResourceManager.GetString("UI_JapaneseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   言語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_LanguageLabel {
            get {
                return ResourceManager.GetString("UI_LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レベル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_LevelLabel {
            get {
                return ResourceManager.GetString("UI_LevelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ローカルサーバーモード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_LocalServerModeLabel {
            get {
                return ResourceManager.GetString("UI_LocalServerModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_NameLabel {
            get {
                return ResourceManager.GetString("UI_NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_PasswordLabel {
            get {
                return ResourceManager.GetString("UI_PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プレイヤーキル数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_PlayerKillsLabel {
            get {
                return ResourceManager.GetString("UI_PlayerKillsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ポート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_PortLabel {
            get {
                return ResourceManager.GetString("UI_PortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   準備完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_ReadyComplete {
            get {
                return ResourceManager.GetString("UI_ReadyComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スコア に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_ScoreLabel {
            get {
                return ResourceManager.GetString("UI_ScoreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_ServerLabel {
            get {
                return ResourceManager.GetString("UI_ServerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定(_S) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_SettingsBT {
            get {
                return ResourceManager.GetString("UI_SettingsBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コマンドリストの表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_ShowCommandListBT {
            get {
                return ResourceManager.GetString("UI_ShowCommandListBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Steam ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_SteamIDLabel {
            get {
                return ResourceManager.GetString("UI_SteamIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Telnet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_TelnetLabel {
            get {
                return ResourceManager.GetString("UI_TelnetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ツール(_T) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_ToolBT {
            get {
                return ResourceManager.GetString("UI_ToolBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップデートの確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_UpdateCheckBT {
            get {
                return ResourceManager.GetString("UI_UpdateCheckBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バージョン情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_VersionBT {
            get {
                return ResourceManager.GetString("UI_VersionBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バージョン情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_VersionLabel {
            get {
                return ResourceManager.GetString("UI_VersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバーの起動を待機中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_WaitingServer {
            get {
                return ResourceManager.GetString("UI_WaitingServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ゾンビキル数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_ZombieKillsLabel {
            get {
                return ResourceManager.GetString("UI_ZombieKillsLabel", resourceCulture);
            }
        }
    }
}
