//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _7dtd_svmanager_fix_mvvm.LangResources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SetupResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SetupResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_7dtd_svmanager_fix_mvvm.LangResources.SetupResource", typeof(SetupResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   実行可能ファイル (*.exe)|*.exe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Filter_ExcutableFile {
            get {
                return ResourceManager.GetString("Filter_ExcutableFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XMLファイル (*.xml)|*.xml|すべてのファイル(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Filter_XmlFile {
            get {
                return ResourceManager.GetString("Filter_XmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_AutoSearchBT {
            get {
                return ResourceManager.GetString("UI_AutoSearchBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_CancelBT {
            get {
                return ResourceManager.GetString("UI_CancelBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_ExitBT {
            get {
                return ResourceManager.GetString("UI_ExitBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   初期設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_NameLabel {
            get {
                return ResourceManager.GetString("UI_NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次へ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_NextBT {
            get {
                return ResourceManager.GetString("UI_NextBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このフォームはSavannah Managerで最低限必要な設定を行います。
        ///進める場合は次へをクリックしてください。
        ///初期設定を後ほど行う場合はキャンセルをクリックしてください。
        ///再度このウィザードを開く場合はツールより開くことができます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Page1Description {
            get {
                return ResourceManager.GetString("UI_Page1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Savannah Managerセットアップウィザードの開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Page1Title {
            get {
                return ResourceManager.GetString("UI_Page1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   7Days To Dieのサーバーファイルを選択してください。Dedicated Serverの場合は7DaysToDieServer.exeを、ゲーム本体の場合は7DaysToDie.exeを選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Page2Description {
            get {
                return ResourceManager.GetString("UI_Page2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバーファイルを選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Page2Title {
            get {
                return ResourceManager.GetString("UI_Page2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   7Days To Dieのサーバーコンフィグファイルを選択してください。serverconfig.xmlがそのファイルです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Page3Description {
            get {
                return ResourceManager.GetString("UI_Page3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバーコンフィグファイルを選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Page3Title {
            get {
                return ResourceManager.GetString("UI_Page3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   これで一通り最低限の設定は終わりです。
        ///最後に右下の終了ボタンをクリックしてください。
        ///あとは再生ボタンをクリックするだけでサーバーが立ち上がります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Page4Description {
            get {
                return ResourceManager.GetString("UI_Page4Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   もうすぐで終わりです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Page4Title {
            get {
                return ResourceManager.GetString("UI_Page4Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   戻る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_PrevBT {
            get {
                return ResourceManager.GetString("UI_PrevBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Steamがインストールされていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_SteamNotInstalled {
            get {
                return ResourceManager.GetString("UI_SteamNotInstalled", resourceCulture);
            }
        }
    }
}
