//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigEditor_mvvm.LangResources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConfigEditor_mvvm.LangResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   終了(_X) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_ExitBT {
            get {
                return ResourceManager.GetString("UI_ExitBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル(_F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_FileBT {
            get {
                return ResourceManager.GetString("UI_FileBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_NewFileBT {
            get {
                return ResourceManager.GetString("UI_NewFileBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_OpenBT {
            get {
                return ResourceManager.GetString("UI_OpenBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前を付けて保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_SaveAsBT {
            get {
                return ResourceManager.GetString("UI_SaveAsBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上書き保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_SaveBT {
            get {
                return ResourceManager.GetString("UI_SaveBT", resourceCulture);
            }
        }
    }
}
